#!/bin/sh
# This creates stuff memory info in cd /sys/class/uio/uio0/maps/map1

echo EBB-PRU-ADC > $SLOTS
cat $SLOTS
lsmod
rmmod uio_pruss
modprobe uio_pruss extram_pool_sz=0x800000


pasm -V3b pruMem.p
pasm -V3b pruADC.p
gcc mem2file.c -o mem2file
gcc getData.c -o getData -lpthread -lprussdrv
